# Generated by Django 3.2.16 on 2024-12-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_group_unique_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_check',
            field=models.ImageField(null=True, upload_to='users/check/', verbose_name='Фото для проверки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Аватар'),
        ),
    ]
