# Generated by Django 3.2.16 on 2024-12-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20241219_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=256, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
