# Generated by Django 3.2.16 on 2024-12-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img/users/avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_check',
            field=models.ImageField(null=True, upload_to='img/users/check/', verbose_name='Фото для проверки'),
        ),
    ]
