# Generated by Django 3.2.16 on 2024-12-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20241219_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Зарегистрирован'),
        ),
    ]
