# Generated by Django 3.2.16 on 2024-12-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Курс'),
        ),
    ]
