# Generated by Django 3.2.16 on 2024-12-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('last_name',), 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.SmallIntegerField(default=1),
        ),
    ]
