# Generated by Django 3.2.16 on 2024-12-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20241218_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='img/teachers/no_content.jpg', upload_to='img/teachers', verbose_name='Фото'),
        ),
    ]
