# Generated by Django 3.2.16 on 2024-12-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='img/teachers/no_content.jpg', upload_to='img/teachers', verbose_name='Фото'),
        ),
    ]
