# Generated by Django 3.2.16 on 2024-11-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20241119_1042'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=256, verbose_name='Аудитория')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_type', models.CharField(choices=[('even', 'Четная неделя'), ('uneven', 'Нечетная неделя')], default='uneven', max_length=256, verbose_name='Вид недели')),
                ('week', models.CharField(choices=[('mn', 'Понедельник'), ('tu', 'Вторник'), ('wd', 'Среда'), ('th', 'Четверг'), ('fr', 'Пятница'), ('st', 'Суббота'), ('sn', 'Воскресенье')], default='mn', max_length=256, verbose_name='День недели')),
                ('order', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=256, verbose_name='Какая пара')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='schedule.classroom')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписании',
            },
        ),
    ]
