# Generated by Django 3.2.16 on 2024-11-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20241119_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='week_day',
            field=models.CharField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота'), ('6', 'Воскресенье')], default='0', max_length=256, verbose_name='День недели'),
        ),
    ]
