# Generated by Django 3.2.16 on 2024-11-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20241124_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='type',
            field=models.CharField(default='пр.', max_length=256, verbose_name='Тип заниятия'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.CharField(max_length=256, null=True, verbose_name='Аудитория'),
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
