# Generated by Django 3.2.16 on 2024-11-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20241124_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.CharField(max_length=256, null=True, verbose_name='Тип заниятия'),
        ),
    ]
