# Generated by Django 3.2.16 on 2024-12-18 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('schedule', '0009_auto_20241218_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='teachers.teacher'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
