# Generated by Django 3.2.16 on 2024-12-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20241218_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
    ]
