# Generated by Django 3.2.16 on 2024-11-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_unique_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_name',
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_subject_name'),
        ),
    ]
