# Generated by Django 3.2.16 on 2024-12-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20241124_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course_work',
            field=models.CharField(default='нет', max_length=256, verbose_name='Курсовая работа'),
        ),
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(default='зачет', max_length=256, verbose_name='Тип сдачи'),
        ),
    ]
