# Generated by Django 3.2.16 on 2024-12-20 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_alter_subject_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('lectures', 'Лекции'), ('practicals', 'Практические'), ('labs', 'Лабораторные'), ('coursework', 'Курсовые'), ('exam', 'Экзамен/Зачет')], max_length=20)),
                ('file', models.FileField(upload_to='subject_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='subjects.subject')),
            ],
        ),
    ]
